"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

Answer:
	4613732
"""
def fib(range=4000000):
    res = [1,2]
    while(res[-1] <= range):
        res+=[res[-1] + res[-2]]
    return res

def even(lista):
    res=[]
    for x in lista:
        if x%2==0:
            res+=[x]
    return res

print sum(even(fib()))
